// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwQnw-rxiMy88yqf-rWUxIuWLTSfiTkEc',
    appId: '1:523426514457:web:c12474ba6a3bed7ef08c88',
    messagingSenderId: '523426514457',
    projectId: 'hairbnb-7eeb9',
    authDomain: 'hairbnb-7eeb9.firebaseapp.com',
    storageBucket: 'hairbnb-7eeb9.firebasestorage.app',
    measurementId: 'G-E9GTDH2YCN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB31XstFcHtrxoOCIDD9inYeAxNuY3Re8Y',
    appId: '1:523426514457:android:14b9e391010b9610f08c88',
    messagingSenderId: '523426514457',
    projectId: 'hairbnb-7eeb9',
    storageBucket: 'hairbnb-7eeb9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPlzRkaXIjKqYEv3GU-Yul21LZ4mek2yk',
    appId: '1:523426514457:ios:c3ac26b7ef90a434f08c88',
    messagingSenderId: '523426514457',
    projectId: 'hairbnb-7eeb9',
    storageBucket: 'hairbnb-7eeb9.firebasestorage.app',
    iosBundleId: 'net.hairbnb.app.hairbnb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPlzRkaXIjKqYEv3GU-Yul21LZ4mek2yk',
    appId: '1:523426514457:ios:c3ac26b7ef90a434f08c88',
    messagingSenderId: '523426514457',
    projectId: 'hairbnb-7eeb9',
    storageBucket: 'hairbnb-7eeb9.firebasestorage.app',
    iosBundleId: 'net.hairbnb.app.hairbnb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwQnw-rxiMy88yqf-rWUxIuWLTSfiTkEc',
    appId: '1:523426514457:web:9c905d9220eeb6dcf08c88',
    messagingSenderId: '523426514457',
    projectId: 'hairbnb-7eeb9',
    authDomain: 'hairbnb-7eeb9.firebaseapp.com',
    storageBucket: 'hairbnb-7eeb9.firebasestorage.app',
    measurementId: 'G-K203D0JWQ5',
  );
}
